### ISSUE TITLE
Problem with KeePassX

### ISSUE THREAD

**Issue by vysinsky** [bil-elmoussaoui/Hardcode-Tray#143]
Hello,
when I run script it endlessly trying to fix `KeePassX` icon. I get this output:

```
The svg file `/usr/share/icons/Numix-Circle/scalable/apps/keepassx.svg` is invalid.
```

I am using latest `master` version of `numix-theme`, `numix-theme-circle` and `Hardcode-Tray`

**Comment by bil-elmoussaoui** [comment]
I see what's the problem , the application icon is used instead of the status one. I will fix that asap

**Comment by bil-elmoussaoui** [comment]
I figured it out; this is due to the missing icons in Numix
The icons should be named 
- keepassx-indicator
- keepassx-locked
Default icons 
![capture du 2016-01-25 15-36-57](https://cloud.githubusercontent.com/assets/7660997/12553765/7cfdd91e-c379-11e5-85b5-cfb717f9340b.png)
Once the icons are added to Numix, run the script again. Can you open a new issue about this in Numix?

**Comment by vysinsky** [comment]
Sure. Thank you!

**Comment by bil-elmoussaoui** [comment]
I will close this! if you have any other issues with keepassx later, please open a new issue! Thanks
