### ISSUE TITLE
Gitter desktop

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#152]
Gitter still uses a hardcoded icon. It is build using chrome as base, as far as I understand, so maybe the icon is located in `nw.pak` (haven't found it though)

**Comment by bil-elmoussaoui** [comment]
I didn't found it neither, i think that the icon is hardcoded in the binary file? don't know if it's possible..

**Comment by wa4557** [comment]
I might be able to filter it out from the binary and replace it. Might be worth a try...

**Comment by bil-elmoussaoui** [comment]
The icon names are here https://github.com/gitterHQ/desktop/tree/master/nwapp/img. I still don't know if they're hardcoded or not;

**Comment by wa4557** [comment]
As far as I can see, the png is not stored in the binary, extracting the png files that are stored directly in the binary only gives different pngs...

**Comment by bil-elmoussaoui** [comment]
Gitter will release a new version of their app soon, lets wait and see if
they will move to Electron?
Le 11 mai 2016 20:32, "Andreas Angerer" <notifications@github.com> a écrit :

As far as I can see, the png is not stored in the binary, extracting the
png files that are stored directly in the binary only gives different
pngs...

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/152#issuecomment-218548769>

**Comment by bil-elmoussaoui** [comment]
It's now possible to fix nwjs apps.
The user must add a new config in the config file with the key `nwjs-bin` which contains the absolute path to the nwjs sdk that must be downloaded and extracted somewhere.
So happy to see this fixed after a year!
