### ISSUE TITLE
Icon for clipit

### ISSUE THREAD

**Issue by edgard** [bil-elmoussaoui/Hardcode-Tray#208]
Hi Bilal!

Would it be possible to fix clipit tray icon? Numix circle includes an icon but it's color and it is out of place on a monochrome tray.

**Comment by bil-elmoussaoui** [comment]
Can you screenshot the tray icon?

**Comment by edgard** [comment]
Sure thing, here it is: https://u.teknik.io/UCj5o.png

Numix circle has
/usr/share/icons/Numix-Circle/48/apps/clipit-trayicon.svg

But it's that colored one.

**Comment by bil-elmoussaoui** [comment]
This cannot be fixed, because the application uses the same icon for the application icon (on the desktop file) and for the tray icon. As you can see in `/usr/share/Numix/22/status/` you will find an icon named `renamed-clipit-trayicon`. We have renamed the icons that had the same status/app icon name. Which caused some issues (the tray icon being displayed instead of the app icon..)

In order to fix this, you can either change the the icon name on your desktop file, and rename the status icon on your theme to the correct icon name, this might fix the issue.
