### ISSUE TITLE
add lantern and alkasir icon

### ISSUE THREAD

**Issue by Chamrosh** [bil-elmoussaoui/Hardcode-Tray#228]
https://getlantern.org/
https://alkasir.com/en/

**Comment by bil-elmoussaoui** [comment]
I just built lantern on my desktop. The icon is stored under /tmp with the name systray_rjbgJW. As the file will be removed once the application is closed, this will make it impossible to theme only if i can access to the source code of the application.I will clone the source code and investigate.

**Comment by bil-elmoussaoui** [comment]
This is sadly hardcoded. As you can see here https://github.com/getlantern/lantern/blob/devel/src/github.com/getlantern/systray/systray_linux.c#L41 
This https://github.com/getlantern/lantern/blob/devel/src/github.com/getlantern/systray/systray_linux.c#L45 will generate a unique icon name. 
The icon is received a bytes data. https://github.com/getlantern/lantern/blob/devel/src/github.com/getlantern/systray/example/icon/iconunix.go
The only solution in order to fix this, is either create a PR to use an indicator icon from the default theme.  My C/C++ coding skills is not that good! but it should be easy to fix this; i will open a PR upstream and hope it will get merged soon

**Comment by bil-elmoussaoui** [comment]
Tried to fix both issues but compiling those applications is really a pain. Reported on both projects upstream and also provided the c++ documentation on how to fix this. 
Closing this, hope they will fix it as soon as possible :+1:
