### ISSUE TITLE
Keepassx icon doesn't change

### ISSUE THREAD

**Issue by mustaqimM** [bil-elmoussaoui/Hardcode-Tray#239]
When running hardcode-tray, it doesn't detect Keepassx, so nothing changes.

**Comment by bil-elmoussaoui** [comment]
Which version if Keepassx are you using ? + check this issue out #173

**Comment by bil-elmoussaoui** [comment]
Also, can you provide the distro, the version of it.

**Comment by mustaqimM** [comment]
I'm on Manjaro KDE 16.10.3, the keepassx version is 2.0.3-1.

**Comment by bil-elmoussaoui** [comment]
It's an upstream issue. We can't do anything about this... I would push a fix upstream if they were using Github... You can add those informations to your report if you wish. 
The issue is due to using the same icon for application name and tray icon. In the source code it's  on `/src/gui/MainWindow.cpp/` Line 503 `m_trayIcon = new QSystemTrayIcon(filePath()->applicationIcon(), this);`

**Comment by bil-elmoussaoui** [comment]
If you have a way to contribute to Keepassx, just let me know and i will push a fix to the main source code.

**Comment by abouvier** [comment]
@bil-elmoussaoui Can you fix it in [keepassxc](https://github.com/keepassxreboot/keepassxc)? It's a more up to date fork, and it's on GitHub :p

**Comment by bil-elmoussaoui** [comment]
@abouvier I will take a look, they seem to have the exact same issue as the older version of keepassx. I will see what i can do ;) i might fix it upstream which is much more better :+1:
