### ISSUE TITLE
Request dark theme to user

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/Hardcode-Tray#257]
Too many applications now provide the possibility to choose between dark and light theme. We shouldn't change both icons using the current theme that the users use. 
We should add a new argument, `--light-theme` `--dark-theme` If those are defined, the icons will be used from there. If not we switch the default `--theme` or to the autodetected theme.

This way we can provide a better experience to the user :+1:

**Comment by varlesh** [comment]
Maybe this not needed? Yes, app have switcher tray icon white/dark... But why this needed really?
Also Papirus not have version for dark icons on tray... because mostly DE use dark panel and white icons on Linux tray. Maybe it's for futures supported themes, but i'm not understand how this will be worked

**Comment by bil-elmoussaoui** [comment]
I will just add --light-theme --dark-theme as arguments, so the user can set both themes in the same time ;)

**Comment by varlesh** [comment]
Any way i'm not understand how this will be worked. Because mostly apps not have dark variant or option for change icon color.
You use icon theme with light tray icons and dark option not needed for you, also if you use dark icons - light option not needed... 
If icon theme not have full dark icons for tray - option dark not solve problem, because others icons will be light...
User change icon theme - run hardcode tray again - it's all.

**Comment by varlesh** [comment]
You wan add this for elementary?

**Comment by bil-elmoussaoui** [comment]
Not really for elementary as i don't use it at all (just for testing). I just don't want to overwrite light icons with dark ones. The default behavior will stay the same, but if the user uses --light-theme and --dark-theme (together), the light icons will be used from the light theme and the dark one from the dark theme.

**Comment by varlesh** [comment]
I know only elementary use this effect for icons (if use light wallpaper):
![image](https://cloud.githubusercontent.com/assets/8083855/21527844/8e3a2330-cd47-11e6-9f8c-fee572f74a3b.png)
But you can disable this:
```
gsettings set org.pantheon.desktop.wingpanel use-transparency false
```
> the light icons will be used from the light theme and the dark one from the dark theme.

Ok, maybe this worked with Numix, but not Papirus  - because dark tray icons not available now (only for KDE color scheme on Plasma 5)

**Comment by bil-elmoussaoui** [comment]
I'm doing this more for Numix! but as i said, it's won't affect neither your theme or any user experience. it's just a plus feature!

**Comment by bil-elmoussaoui** [comment]
Added on master. The script will now detect if the original icon name has the keyword "dark" or "light" and use the correct theme if it's defined by the user using `--light-theme` and `--dark-theme`. Both work together, and only if it's the case!
