### ISSUE TITLE
Crashes on Reversion

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#306]
### Specifications
- Hardcode-Tray version : 3.6.5
- Distribution : Ubuntu 16.10
- Gtk version : 3.20.9
- Inkscape version : 0.91
- Cairo version : 1.14.6
- Sni-qt version: 0.2.7
- Application name :  Rambox
- Application version : 0.5.2

### Expected behavior and actual behavior

Expected: Revert changes made to Rambox
Actual: Program crashes with file not found error

### Steps to reproduce the problem
1. Install Rambox 0.5.0
2. Run hardcode-tray to fix the icon
3. Update Rambox from 0.5.0 to 0.5.2
4. Try to revert the previous changes made

**Comment by bil-elmoussaoui** [comment]
This is indeed not so good! But i can't really do anything about it, the tray icons are replaced on the asar file. Which stores some libraries used by electron applications too! once you revert an old asar package to a newer version of the same application it will normally crash as some  good is missing. I can't detect the version number of any application out there, each distro out there has a different packaging system, people can install the application from the source code and so on...
The only thing i can think about, is instead of backing up the whole binary file, we backup only the modified icons. But again if the images locations changes on the newer update it won't work :P 
@wa4557 What do you think about this issue?

**Comment by Foggalong** [comment]
It sounds like there should be at least a check that the file exists before attempting to do anything with it though. And cool, I'll check out that issue :)

**Comment by bil-elmoussaoui** [comment]
We already check if the file exists in the binary file 👍 let's hear what @wa4557 thinks about it and i will fix it as soon as possible! :D

**Comment by wa4557** [comment]
I would remove the possibility to revert electron icons then (or any other apps wher we replace icons in the binary file). That's causing more problems than it solves, and we don't have to store this large asar files

**Comment by bil-elmoussaoui** [comment]
Yeah :( in some applications those files are more than 100M ! I will try to backup the png file, test it with updating/reversing back after and see if it works correctly. If it does i will push it to master if not i will remove the backup from the binary applications

**Comment by bil-elmoussaoui** [comment]
The master branch now just back up the png files :+1: 
![screenshot from 2017-05-23 17-21-52](https://cloud.githubusercontent.com/assets/7660997/26361783/567a5912-3fdc-11e7-889b-cd9f288c14a3.png)
Tried it for every app out there and it works perfectly!
