### ISSUE TITLE
Chromium indicator doesn't change to a custom icon

### ISSUE THREAD

**Issue by skintigth** [bil-elmoussaoui/Hardcode-Tray#314]
### Specifications
- Hardcode-Tray version : `v3.6.5`
- Distribution : `Arch Linux x64`
- Gtk version : ``
- Inkscape version : `0.92.0 r`
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `Chromium / chromum-browser`
- Application version : `56.0.2924.87 (64-bit)`

### Expected behavior and actual behavior
![captura de pantalla_2017-02-17_12-04-02](https://cloud.githubusercontent.com/assets/6403537/23077152/f5027ea8-f508-11e6-9e4b-32e9c56346d0.png)

I expected the white icon (Added with gimp in the screenshot), but the stills is the blue one

### Steps to reproduce the problem
1. I used `hardcode-tray --only chromium --path /home/skintigth/chromium.svg --apply` it says its applied, I restart chromium but the icon not change 
2. If I use `hardcode-tray --only chromium --path /home/skintigth/ --apply` it says its applied, I restart chromium then the icon disappears 
3.And with this `hardcode-tray --only chromium-browser --path /home/skintigth/chromium.svg --apply` shows "No apps to fix"

**Comment by bil-elmoussaoui** [comment]
Hello,
I think you've misunderstood how things work on Hardcode-Tray. The --path argument is to specify the application installation path in order to patch the application you want.  And not the icon path.

If you want to use your icon all you have to do is to put the current icons that you want to use in the current theme you're using or any other one (Just copy those svg files to the theme path under status or panel folder). The icon name must use the same icon names as used by Hardcode-tray see this example for Chromium https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/database/chromium.json#L21 The icon name is `google-chrome-tray`. Once it's done you have to refresh icon cache of your theme (or reboot) and run `hardcode-tray --theme MYTHEMENAME --only chromium --apply`
And everything will work as expected

**Comment by bil-elmoussaoui** [comment]
Closing, reopen if you need more help :)
