### ISSUE TITLE
Hangouts Chrome extension breaks

### ISSUE THREAD

**Issue by yochananmarqos** [bil-elmoussaoui/Hardcode-Tray#330]
### Specifications
- Hardcode-Tray version : `3.66 / 3.5.2.1~737~ubuntu16.04.1`
- Distribution : `Linux Mint 18.1 "Serena" Xfce Edition`
- Gtk version : `2.24.30-1ubuntu1 / 3.18.9-1ubuntu3.2`
- Inkscape version : `0.91 r13725` if installed
- Cairo version : `1.0.19-1` if installed
- Sni-qt version: `0.2.7+20161212~10~ubuntu16.04.1` if installed
- Application name :  `Google Hangouts / Google Chrome`
- Application version : `2017.110.418.2 / 57.0.2987.98`

### Expected behavior and actual behavior
Expected: Icon is applied
Actual: Icon is applied but breaks extension

### Steps to reproduce the problem
1. `hardcode-tray --theme Papirus --conversion-tool Inkscape --apply`
2. Start Chrome, Hangouts extension will disappear
3. Check Extensions, extension will be corrupted with option to repair

**Comment by bil-elmoussaoui** [comment]
The hangouts extension wasn't working for me so i've removed it for a while. And suddenly it's working again, at least on my case that's why i've added it back. I don't know if i have enabled something on Chrome but it doesn't seem to be the case...So really don't know how should i handle this. Maybe adding a config file where you can set a blacklist of apps that you don't want to be fixed ?

**Comment by yochananmarqos** [comment]
A blacklist is a great idea either way.

**Comment by bil-elmoussaoui** [comment]
i will add it to my to-do list for the 4.0 (or maybe before)

**Comment by bil-elmoussaoui** [comment]
Fixed on master. See https://github.com/bil-elmoussaoui/Hardcode-Tray#config-file
