### ISSUE TITLE
Add support for KeePassXC tray icon

### ISSUE THREAD

**Issue by z-engine** [bil-elmoussaoui/Hardcode-Tray#341]
[KeePassXC](https://github.com/keepassxreboot/keepassxc) is the fork of the keepassx, which is much more actively developed, has a number of more cool features, looks more natively in kde5, because it is based on QT5 and does not have bugs inherent in keepassx (auto-type break layout #[bug584](https://dev.keepassx.org/issues/584), for example)

![](https://imgur.com/AjP0V8M.png)

**Comment by bil-elmoussaoui** [comment]
The icons are not hardcoded. You can find them under `/usr/share/icons/hicolor/`
The icons are
- `keepassxc`
- `keepassxc-dark`
- `keepassxc-locked`

The normal tray icon won't work as expected as it's using the same icon name as the application icon name. Which causes some issues with Gtk Icon themes. Please report that upstream in order to rename the icon name to something else
Closing.
