### ISSUE TITLE
Icons have no shadows

### ISSUE THREAD

**Issue by Feichtmeier** [bil-elmoussaoui/Hardcode-Tray#349]
### Specifications
- Hardcode-Tray version : `3.7`
- Distribution : `Ubuntu GNOME 16.10`
- Gtk version : `3.20`
- Inkscape version : `0.91` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `GNOME-Shell`
- Application version : `3.20.4`

The gnome-shell indicatos have shadows, which you see when you install https://extensions.gnome.org/extension/885/dynamic-top-bar/ the hardcode-tray indicators have none.

### Steps to
![bildschirmfoto vom 2017-05-04 13-50-00](https://cloud.githubusercontent.com/assets/15329494/25702288/9643ff14-30d0-11e7-9d90-dd5be79fb718.png)
 reproduce the problem
1. Use hardcod-tray icons in gnome.shell

**Comment by bil-elmoussaoui** [comment]
It's just impossible, in order to have shadows the icons must be SVG & Symbolic which isn't the case with all those Hardcoded Tray icons and i can do nothing about it.... and in order to change the color of the tray icons take a look at the possible options here https://github.com/bil-elmoussaoui/Hardcode-Tray#options
Anyway, it's an invalid issue...
