### ISSUE TITLE
App request: Ring

### ISSUE THREAD

**Issue by matteosecli** [bil-elmoussaoui/Hardcode-Tray#376]
Hello, could you please add [Ring](https://ring.cx/) to the list of supported applications? I use Numix Circle, which already has an icon for the app, but the app itself shows in tray the same icon that you find in the dash, i.e. this one: https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/ring.svg.
I attach a screenshot of my tray just to be clearer (sorry for the low res!).
![schermata del 2017-06-11 14-29-46](https://user-images.githubusercontent.com/4618521/27011029-99b8ded0-4eb2-11e7-9858-8d661de3aa17.png)
~~I will also open an issue at the Numix side~~ I've also opened an issue at https://github.com/numixproject/numix-icon-theme/issues/1227 so that they can make a proper monochrome replacement for the tray icon.
Thank you! :smile:

**Comment by bil-elmoussaoui** [comment]
Hey, 
Thanks for your request. I can't do anything about it. The icon is hardcoded to use the same icon as the application icon name. Which causes this issue. You can see that by yourself by checking the source code that can be found here : https://gerrit-ring.savoirfairelinux.com/#/admin/projects/
On the ring-gnome project, file `ringmainwindow.cpp` at the line 1306. 
```cpp
 /* set menu icon */
    GdkPixbuf* image_ring = gdk_pixbuf_new_from_resource_at_scale("/cx/ring/RingGnome/ring-symbol-blue",
                                                                  -1, 16, TRUE, &error);
    if (image_ring == NULL) {
        g_debug("Could not load icon: %s", error->message);
        g_clear_error(&error);
    } else
        gtk_image_set_from_pixbuf(GTK_IMAGE(priv->image_ring), image_ring);
```

This should be reported to ring devs instead and ask for a different icon name for the menu icon instead of using the same icon name for both application icon & the menu icon

**Comment by matteosecli** [comment]
Sorry for the delay! Thank you, I see...
I'll report to them and see if they want to use a different icon name for the tray icon.
Keep going with this nice project, btw! It's just great! :smiley:

**Comment by cement-head** [comment]
Yeah, this needs to be fixed ASAP.  Looks terrible.
