### ISSUE TITLE
Steam Icon Super Tiny

### ISSUE THREAD

**Issue by garchomps** [bil-elmoussaoui/Hardcode-Tray#396]
### Specifications
- Hardcode-Tray version : `3.9`
- Distribution : `Xubuntu 17.04`
- Gtk version : `3.22.11-0ubuntu3`
- Inkscape version : `0.92.1 r15371` if installed
- Cairo version : `1.14.8-1ubuntu0ppa1` if installed
- Sni-qt version: `0.2.7+20161212~10~ubuntu17.04.1` if installed
- Application name :  `Steam`
- Application version : `1496897923`

### Steps to reproduce the problem
1. Run hardcode-tray to convert Steam's tray icon more than once. 

After doing so unintentionally the Steam tray icon has become super tiny compared to the rest. Attached a screenshot. This doesn't seem to affect any other applications supported by hardcore-tray. I am also unable to revert it to its original state. 

![hardcode-tray](https://user-images.githubusercontent.com/6912559/27608446-9c2b6250-5b55-11e7-817f-a182ba87210d.png)

**Comment by bil-elmoussaoui** [comment]
The icon is located on `/usr/share/pixmaps/`. Can you upload the icon file? + the logs that can be found on `/tmp/Hardcode-Tray/`?

**Comment by woomba** [comment]
### Specifications

- Hardcode-Tray version : `3.9`
- Distribution : `Ubuntu GNOME 17.04`
- Gtk version : `3.22.11-0ubuntu3`
- Inkscape version : `0.92.1 r15371` if installed
- Cairo version : `-` if installed
- Sni-qt version: `-` if installed
- Application name : `Steam`
- Application version : `1496897923`

### Expected behavior and actual behavior

### Steps to reproduce the problem
Same issue as described above. Ran hardcode-tray to convert icons (Skype, Steam, Slack, Chrome, Vivaldi, Telegram) and the Steam tray icon is tiny now. The others are fine.  
Icons and logs attached.

![2017-06-30 07_54_34-ubuntu 64-bit - vmware workstation](https://user-images.githubusercontent.com/25892893/27712296-c4f0a324-5d69-11e7-8a22-f45641dc5c28.png)

[logs.zip](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1113634/logs.zip)
[icons.zip](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1113637/icons.zip)

**Comment by bil-elmoussaoui** [comment]
The icon size is correct. As you can see it's 22x22. if you want a bigger icon for steam tray icon, just force that using `hardcode-tray --size 24 --only steam`It's might also be an issue with the extension you're using to force the tray icon to be on top on GNOME. As the generated icon looks perfectly fine.

**Comment by woomba** [comment]
Reinstalled Steam and forced the bigger icon but it's tiny again. The extension I'm using is TopIcons Plus. Disabling it still shows the small icon:

![2017-06-30 11_02_48-ubuntu 64-bit - vmware workstation](https://user-images.githubusercontent.com/25892893/27716779-14bb9566-5d84-11e7-92d6-eabddcc45702.png)

As mentioned in the first post, I am not able to revert it to its original state unless I reinstall steam.

**Comment by bil-elmoussaoui** [comment]
This issue is unrelated. it's a known issue on GNOME Shell. You can try by yourself or look at GNOME's bug tracker for more information.

**Comment by bil-elmoussaoui** [comment]
+ I'm using Gnome 3.25 on Arch with Steam too and the icon works just fine. Please try to tweak the icon size using TopIconsPlus (there's a setting for tray icons size)

**Comment by garchomps** [comment]
![steam_tray_mono](https://user-images.githubusercontent.com/6912559/27756636-459d71ac-5dc7-11e7-91d5-9738bff50a48.png)

[DEBUG] 2017-06-30 19:01:25 DE: Xfce
[DEBUG] 2017-06-30 19:01:25 Config file: Not found.
[DEBUG] 2017-06-30 19:01:25 Arguments/Icon Size: 24
[DEBUG] 2017-06-30 19:01:25 Arguments/Theme: Papirus
[DEBUG] 2017-06-30 19:01:25 Arguments/Conversion Tool: Inkscape
[DEBUG] 2017-06-30 19:01:25 Arguments/Only: steam
[DEBUG] 2017-06-30 19:01:26 Config/Backup Ignore: False
[DEBUG] 2017-06-30 19:01:26 Create new backup folder for Steam
[DEBUG] 2017-06-30 19:01:26 Creating directory: /home/user/.config/Hardcode-Tray/Steam/30-06-2017_19-01-26/
[DEBUG] 2017-06-30 19:01:26 Executing command: inkscape -z -f /usr/share/icons/Papirus/24x24/panel/steam_tray_mono.svg -e /usr/share/pixmaps/steam_tray_mono.png -w 24 -h 24

Sorry for the late reply I've been busy as of late.

**Comment by varlesh** [comment]
For XFCE:
Steam use icon theme from system icon theme, why hardcode-tray available this on database?
@garchomps See your screenshot, mostly icons blured, because panel size very small. I recommend increase panel size to 26px or 28px:
![image](https://user-images.githubusercontent.com/8083855/27856997-0d0f92d0-6181-11e7-9cec-87583cd0288c.png)
Also for notification use 22px or 24px and dor hardcode-tray too similar.
See https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#manual-fixes

**Comment by bil-elmoussaoui** [comment]
@varlesh As I've explained before. It's the same case as Guake terminal, the icon can not be overridden in some systems.That's why I've added it. Also, there's an option in the config file called `blacklist` where you can add the apps that you don't to be fixed. If your Steam icon works perfectly, all you have to do is add it to the blacklist :)

**Comment by garchomps** [comment]
@varlesh I've tried all of what you recommended, the icon still will not scale with the size of the system tray and stays the same size. 
@bil-elmoussaoui I'd like to know what config file contains this blacklist option so I can so go back to the original steam icon as reverting it does not seem to fix it? Thanks.

**Comment by bil-elmoussaoui** [comment]
@garchomps https://github.com/bil-elmoussaoui/Hardcode-Tray#config-file
Here you go

**Comment by garchomps** [comment]
The blacklist seems to be working, my steam icon is still super tiny though :(

**Comment by bil-elmoussaoui** [comment]
Well, try reinstalling steam in that case. Or replace the icon manually with a bigger one. Plus, there's an upstream issue on Valve bug tracker here on Github. Which should fix this issue (I hope)

**Comment by garchomps** [comment]
Reinstalling Steam seemed to fix it, thanks!

**Comment by bil-elmoussaoui** [comment]
Happy to hear that :)

**Comment by rauldipeas** [comment]
I'm facing the same issue here, I tried to reinstall Steam, but it won't fix.

Steam already on the blacklist, I'm not using hardcode-tray on it.

If I delete `steam_tray` related icons on Papirus, it's not showing fallback icon on `/usr/share/pixmaps` folder.

![image](https://user-images.githubusercontent.com/12108031/131647605-11563966-d5d1-427c-89ca-f30a82bfd2aa.png)
