### ISSUE TITLE
Jetbrain Toolbox, Netease music support !

### ISSUE THREAD

**Issue by SeptemberHX** [bil-elmoussaoui/Hardcode-Tray#407]
Please support jetbrain toolbox !! You can find it here: [Jetbrain toolbox](https://www.jetbrains.com/toolbox/)  
![image](https://user-images.githubusercontent.com/18042424/28493429-bbb0c540-6f49-11e7-9e84-56160dffff83.png)

And another app: Netease music !! [netease music download link](http://s1.music.126.net/download/pc/netease-cloud-music_1.0.0-2_amd64_ubuntu16.04.deb)
![image](https://user-images.githubusercontent.com/18042424/28493431-cd29e22a-6f49-11e7-8ad6-37d12985e9bd.png)

PomodoneAPP: [PomodoneApp](https://pomodoneapp.com/)
![image](https://user-images.githubusercontent.com/18042424/28498129-fc6538f2-6fc9-11e7-922a-45922074e37c.png)

**Comment by bil-elmoussaoui** [comment]
Jetbrain Toolbox has the icon hardcoded on the binary see #297 
The Netease music seems to be using NodeWebkit? But their binary is quite different than the rest of the NodeWebkit apps. As the application is closed source, they might have changed the way the binary is made... i can't investigate further without the source code :(

**Comment by bil-elmoussaoui** [comment]
PomoDoneApp support is now on master

**Comment by SeptemberHX** [comment]
It doesn't work ... Pomodone APP still have the original tray icon.
I have checked the pomodoneapp.json and it seems everything is right.

So, how to print the log of hardcode-tray ? I think there may be something useful in the log.

**Comment by bil-elmoussaoui** [comment]
The icon theme you're using must add a support for this application.

**Comment by SeptemberHX** [comment]
Thanks for that ! After I put some icons in my icon theme folder, it works.

Another application request: Nozbe, [offical site](https://nozbe.com/)
Build with electron I think. It has the same folder structure as PomodoneApp

Thanks for your fantastic work !!!!!

**Comment by bil-elmoussaoui** [comment]
Nozbe needs some specific work in order to make things works. They indeed uses Electron. If you install the application, you will find under the `install_path/resources` a file named `app.asar` that you can extract using `asar`module from npm `sudo npm -g i asar`. Once you've extracted that file, the icon for the tray menu is created in `app/utils/index.js`. You will find a function that creates the icon for Linux `buildIconForLinux` this function will read a binary file which contains `data:image/png;base64, the binary content of the image encoded using base 64`. Currently, our Electron module can't handle anything like that, and it's so specific for this application. I won't sadly add a support for it for now, there are many important issues to fix. If you want, you can open an issue upstream and if it's got fixed I will add the support here on Hardcode-Tray.

I'm going to close this issue as the two other reported apps can not be fixed at the moment until we figure out a way to replace the icons in the binary file which will work on all the cases no matter what version you're using.
