### ISSUE TITLE
Hardcode-Tray stopped working, reinstalled, won't install from ppa

### ISSUE THREAD

**Issue by Feichtmeier** [bil-elmoussaoui/Hardcode-Tray#413]
I can't check the version because:

/opt/Hardcode-Tray$ hardcode-tray --version
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 38, in <module>
    from HardcodeTray.app import App
ImportError: No module named 'HardcodeTray'

Hmpf. I reinstalled hardcode-tray many times it still gives the same error

hardcode-tray 
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 38, in <module>
    from HardcodeTray.app import App
ImportError: No module named 'HardcodeTray'

**Comment by bil-elmoussaoui** [comment]
Hey sorry for that, this bug was introduced once we were able to update the PPA to use the meson build system.
And this bug is already fixed on master. The auto build should be triggered in a few hours ( @wa4557 can you do that manually ?)
For now; if you really need Hardcode-Tray you can still compile it from source.  Otherwise, a new update should land by tomorrow (we hope that launchpad won't break anything anymore)

**Comment by wa4557** [comment]
@Feichtmeier Should work now. If you install again from PPA you should get a working version

**Comment by Feichtmeier** [comment]
Yes it works now! Thank you!
