### ISSUE TITLE
Add  persepolis 

### ISSUE THREAD

**Issue by behroozramezani** [bil-elmoussaoui/Hardcode-Tray#445]
- Application name :  persepolis
[https://persepolisdm.github.io/](https://persepolisdm.github.io/)
Tray icons:
![screenshot_20170915_014708](https://user-images.githubusercontent.com/17659342/30456195-e0945708-99b7-11e7-9c08-024368dc8631.png)

**Comment by bil-elmoussaoui** [comment]
I will see what i can do as soon as possible

**Comment by bil-elmoussaoui** [comment]
I looked a bit on the source code of the application, it seems that the tray icon is not hardcoded at all. They just use the same icon name for the tray icon and the application icon.
See here https://github.com/persepolisdm/persepolis/blob/f24bdb9b18f78d26ffdbe4ac0596f590bb8bcd64/persepolis/scripts/mainwindow.py#L744-L745
This should be reported upstream, so they can use another icon name like `persepolis-tray` or something else.
There's nothing i can do about this from my side. If the devs agrees, i might open a PR upstream when i have some free time.

Please paste the link of the issue here so others can subscribe to it, thanks 👍
