### ISSUE TITLE
Merge projects... it's possible?

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#491]
Maybe better solution merged this projects to single?:
- Hardcode-Tray
- Hardcode-Fixer
- StartupWMClassFixer

Reasons:
- all this applications have same goal
- It's comfortable for users
- single application, single repository
- run once and all fixed

For example command:
`sudo -E hardcode-fix-complete apps tray wmclass`

About hardcode-tray - i think why not use only RSVGConvert? Other options like size/theme - get from theme config files or dconf/gconf keys or used from hidden config file on user home directory:
```
#hardcode-tray
theme: Papirus
size: 22
conversion-tool: RSVGConvert
#this list apps will be fixed, if empty - fixed all apps
apps: telegram, whatsapp
```
@bil-elmoussaoui @Foggalong What you think?

**Comment by bil-elmoussaoui** [comment]
I don't think it's a good idea at all. Every project has a different purpose and different way of dealing with everything. We require dependencies that shouldn't be needed if you want to just fix a hardcoded desktop application icon. 
You can always, add an alias on your .bashrc or .zshrc file to apply the three scripts at once :)

**Comment by Foggalong** [comment]
Yeah likewise disagree: I don't have to use StartWMClassFixer on any of my setups because none of the DEs/WMs I use are affected by it, and I only have to use Hardcode-Tray on my desktop because that's the only machine on which apps I use have hardcoded tray icons. That means on my other machines I'd be installing a lot of functionality and dependencies I didn't need. An especial concern because on Fedora getting the patched version of sni-qt means compiling it from scratch, which I don't want to waste time doing if I'm only using the fixer element.

**Comment by bil-elmoussaoui** [comment]
@Foggalong the dependencies list is just librsvg nothing more :p sni-qt is only if you're using any Qt apps. But yeah every script has a different purpose, so I don't see any reason to merge them

**Comment by varlesh** [comment]
Ok, guys it's only suggestion )
