### ISSUE TITLE
Invalid CSV

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#5]
The `db.csv` file isn't valid. [Github provides a nice feature for debugging though](https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/db.csv) so it shouldn't be too hard to fix :)

**Comment by bil-elmoussaoui** [comment]
Well, i knew about this but i have no idea(at the moment) how to fix this. The github can't read a csv file with more than 8 rows by line (i guess). But the python module does. 
To explain why i chose that, every line is for a specific application. For example touchpad-indicator the line in db.csv is like this 
The app name, the hardcoded directory, icon1,icon2,icon3.. Iconx 
So some apps might have too many icons => too many rows in a line. 
I was going to use json so i can have only three rows and the third one is for icons but it won't be that easy for users to add other apps. 
That being said, but i'm open for any ideas. 

Thank you for reporting this !

**Comment by Foggalong** [comment]
Ah, I think I see how it works now. Yeah, I'm not sure how you'd go about fixing that because as you say every line would be different :(

You can do blank "cells" in CSV by just doing `,,` but I have no idea if that would help or make things more complicated.

**Comment by bil-elmoussaoui** [comment]
I thought about putting every icon in a line but that will make the code a little bit complicated. I will think about this ;)

**Comment by palob** [comment]
How does it look in a text editor? Maybe there is something wrong with the newline characters?

**Comment by bil-elmoussaoui** [comment]
First, thank your comment. But i don't think its the newline character as the csv module in python dosent show any issues/bugs.

The problem here is that db.csv is not a valid file for github. And i don't have any idea how to fix this. I thought about putting every icon in a line like this :
App-name1,hardcod directory, icon1
App-name1,hardcod directory, icon2
.. 
.. 
App-name2,hardcod directory, icon1 
.. 
.. 

That will fix this and the db.csv will be a valid file for github. But that will not be the nicest way to fix it !

**Comment by bil-elmoussaoui** [comment]
This is fixed now :dancer:
